services:
  ethan-portfolio:
    build: .
    ports:
      - "127.0.0.1:${PORT:-3000}:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - npm-public

networks:
  npm-public:
    external: true
